using AuthorGenderStudy
using Base.Test
using NamedTuples

using AuthorGenderStudy: extract_data
@testset "extract_data" begin
    line = """{"entities":["Apoptosis","Bromodeoxyuridine","Cell Cycle","Cell Proliferation","Claudin-1","Computing the permanent","Edema","Flavonoids","Glioma","Implants","In Situ Nick-End Labeling","Neoplasms","Permeability","Proliferating Cell Nuclear Antigen","Regulation","TJP1 gene","Tight Junctions","Zero suppression","caspase-3","caspase-9","hesperetin","recurrent childhood brain stem glioma"],"journalVolume":"","journalPages":"","pmid":"","year":2016,"outCitations":["b83eb1c0a2df17d9945f08b5efed1f3f388052fa","bb644bf0f2a3e2f148fd1911ff87ee5f5e71955b","b811f8c88798a1334937ecdf705aefe76c0d5e01"],"s2Url":"https://semanticscholar.org/paper/6c85101b5de071af3118d34d2575d3503d83ef19","s2PdfUrl":"http://pdfs.semanticscholar.org/6c85/101b5de071af3118d34d2575d3503d83ef19.pdf","id":"6c85101b5de071af3118d34d2575d3503d83ef19","authors":[{"name":"Xin-hua Zhang","ids":["1709273"]},{"name":"Ning-ning Zhang","ids":["8388022"]},{"name":"Xian-bing Meng","ids":["31521137"]},{"name":"Yang Zhang","ids":["1698138"]},{"name":"Yun Qian","ids":["2259704"]},{"name":"Yun-jie Xie","ids":["11180136"]}],"journalName":"","paperAbstract":"Hesperetin is a plant flavonoid known for its anti-oxidant and anti-cancer properties. The effect of hesperetin treatment on cerebrally implanted C6 glioma cells in rats was studied. C6 tumours were implanted in rats (n=20). The animals with C6 gliomas were treated with hesperetin (10 and 20 mg/kg/ day). Tumour weight, survival of animals, regional tumour permeability analysis was performed. Moreover, the concentration of Bax, bcl-2, Caspase-3, Caspase-9, Claudin-1, Cyclin B1, Cyclin D1, PCNA, VEGF, VEGFR2 and ZO-1 was also determined. The proliferation of glioma cells was also estimated by TUNEL and BrdU staining. Prolonged survival was observed in animals with C6 gliomas when treated with hesperetin. The treatment also attenuated cell proliferation, increased apoptosis and caused arrest of cell cycle, as evident from the differential expression of PCNA, Caspase-3, Caspase-9, Bax/bcl-2, Cyclin B1 and Cyclin D1. Hesperetin treatment of C6 gliomas caused a marked decrease in the tumour permeability and oedema and increased expression of tight junction-associated proteins. Hesperetin treatment also down-regulated the HIF-1a/VEGF/VEGFR2 pathway. We could conclude that hesperetin possesses anti-tumour properties in implanted C6 glioma cells in rats. Therefore, hesperetin treatment may be effective against malignant brain gliomas, functioning by attenuating the growth of tumour and suppression of oedema.","inCitations":[],"pdfUrls":["http://www.alliedacademies.org/articles/hesperetin-inhibits-the-proliferation-of-cerebrally-implanted-c6-glioma-and-involves-suppression-of-hif1vegf-pathway-in-rats.pdf"],"title":"Hesperetin inhibits the proliferation of cerebrally implanted C6 glioma and involves suppression of HIF-1α/VEGF pathway in rats","doi":"","sources":[],"doiUrl":"","venue":""}"""

    @test extract_data(line)  == @NT(authors = String["Xin-hua Zhang", "Ning-ning Zhang", "Xian-bing Meng", "Yang Zhang", "Yun Qian", "Yun-jie Xie"], paper_abstract = "Hesperetin is a plant flavonoid known for its anti-oxidant and anti-cancer properties. The effect of hesperetin treatment on cerebrally implanted C6 glioma cells in rats was studied. C6 tumours were implanted in rats (n=20). The animals with C6 gliomas were treated with hesperetin (10 and 20 mg/kg/ day). Tumour weight, survival of animals, regional tumour permeability analysis was performed. Moreover, the concentration of Bax, bcl-2, Caspase-3, Caspase-9, Claudin-1, Cyclin B1, Cyclin D1, PCNA, VEGF, VEGFR2 and ZO-1 was also determined. The proliferation of glioma cells was also estimated by TUNEL and BrdU staining. Prolonged survival was observed in animals with C6 gliomas when treated with hesperetin. The treatment also attenuated cell proliferation, increased apoptosis and caused arrest of cell cycle, as evident from the differential expression of PCNA, Caspase-3, Caspase-9, Bax/bcl-2, Cyclin B1 and Cyclin D1. Hesperetin treatment of C6 gliomas caused a marked decrease in the tumour permeability and oedema and increased expression of tight junction-associated proteins. Hesperetin treatment also down-regulated the HIF-1a/VEGF/VEGFR2 pathway. We could conclude that hesperetin possesses anti-tumour properties in implanted C6 glioma cells in rats. Therefore, hesperetin treatment may be effective against malignant brain gliomas, functioning by attenuating the growth of tumour and suppression of oedema.")

end
